#define NautilusFileInfo    CajaFileInfo
#define NautilusMenuItem    CajaMenuItem
#define NautilusMenuProvider    CajaMenuProvider
#define NautilusMenuProviderIface    CajaMenuProviderIface
#define nautilus_file_info_get_file_type    caja_file_info_get_file_type
#define nautilus_file_info_get_location    caja_file_info_get_location
#define nautilus_file_info_get_name    caja_file_info_get_name
#define nautilus_file_info_get_parent_location    caja_file_info_get_parent_location
#define nautilus_file_info_get_uri    caja_file_info_get_uri
#define nautilus_file_info_get_uri_scheme    caja_file_info_get_uri_scheme
#define nautilus_file_info_is_directory    caja_file_info_is_directory
#define nautilus_menu_item_new    caja_menu_item_new
#define nautilus_module_initialize    caja_module_initialize
#define nautilus_module_list_types    caja_module_list_types
#define nautilus_module_shutdown    caja_module_shutdown
#define NAUTILUS_TYPE_MENU_PROVIDER    CAJA_TYPE_MENU_PROVIDER
